### ISSUE TITLE
Wrong/no time zone conversion

### ISSUE THREAD

**Issue by phabegger** [Elektron1c97/eml_to_pdf#2]
NOW:
![bildschirmfoto 2016-06-17 um 16 38 24](https://cloud.githubusercontent.com/assets/485600/16154174/ff690fb2-34a9-11e6-9d5c-9c3743baee2a.png)

CORRECT:
![bildschirmfoto 2016-06-17 um 16 38 35](https://cloud.githubusercontent.com/assets/485600/16154176/018b11c8-34aa-11e6-8bb0-3ead2041849d.png)

EML-Header reads as follows:
...
Date: Fri, 17 Jun 2016 14:32:23 +0000
...

Two hours off (should be printed in CET, i.d. UTC+2)

**Comment by siegy22** [comment]
With `0.4.0` we can now use a block to configure how the date should be formatted. This makes it really easy to use integrated systems like I18n.
